
PREFIX rdfs:     <http://www.w3.org/2000/01/rdf-schema#>


DELETE DATA 
{
   GRAPH <http://vitro.mannlib.cornell.edu/default/vitro-kb-2>{ 
    
    <http://orbis.uaslp.mx/vivo/individual/n70532>
    rdfs:label "Moncada González Benjamín ".

}}