
PREFIX rdf:      <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:     <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:      <http://www.w3.org/2001/XMLSchema#>
PREFIX owl:      <http://www.w3.org/2002/07/owl#>
PREFIX swrl:     <http://www.w3.org/2003/11/swrl#>
PREFIX swrlb:    <http://www.w3.org/2003/11/swrlb#>
PREFIX vitro:    <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>
PREFIX bibo:     <http://purl.org/ontology/bibo/>
PREFIX c4o:      <http://purl.org/spar/c4o/>
PREFIX cito:     <http://purl.org/spar/cito/>
PREFIX event:    <http://purl.org/NET/c4dm/event.owl#>
PREFIX fabio:    <http://purl.org/spar/fabio/>
PREFIX foaf:     <http://xmlns.com/foaf/0.1/>
PREFIX geo:      <http://aims.fao.org/aos/geopolitical.owl#>
PREFIX obo:      <http://purl.obolibrary.org/obo/>
PREFIX ocrer:    <http://purl.org/net/OCRe/research.owl#>
PREFIX ocresd:   <http://purl.org/net/OCRe/study_design.owl#>
PREFIX skos:     <http://www.w3.org/2004/02/skos/core#>
PREFIX vcard:    <http://www.w3.org/2006/vcard/ns#>
PREFIX vitro-public: <http://vitro.mannlib.cornell.edu/ns/vitro/public#>
PREFIX vivo:     <http://vivoweb.org/ontology/core#>
PREFIX scires:   <http://vivoweb.org/ontology/scientific-research#>
PREFIX fo: <http://www.w3.org/1999/XSL/Format#>


SELECT DISTINCT  ?Investigador ?RolLabel ?TesisLabel
WHERE {
  
    # Todos los recursos de la clase "Position" que se relacionan con la dependencia
    ?Positions a vivo:Position;
             vivo:relates <http://orbis.uaslp.mx/vivo/individual/DES00000022>.

    # Todas las posiciones en las que la Posicion se relacionen mediante la propiedad "relates"
	?Positions vivo:relates ?Investigadores.
    # De las posiciones anteriores, todas aquellas en la que la clase relacionada sea "FacultyMember"
	?Investigadores a vivo:FacultyMember.  
  
    ?Rol obo:RO_0000052 ?Investigadores; 
         #a vivo:ReviewerRole;
    	vivo:roleContributesTo ?Tesis. 
       
  
    ?Investigadores rdfs:label ?Investigador.
    ?Rol rdfs:label ?RolLabel.
  	?Tesis rdfs:label ?TesisLabel
  	
    # Se filtran los programas bajo el criterio de ser programas de posgrado, se buscan aquellos
    # que contengan las palabras "Posgrado", "Maestría o "Doctorado"
    #FILTER(regex(?ProgLabel,"(Posgrado|Maestría|Doctorado)","i"))
  
  
}


PREFIX rdf:      <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:     <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:      <http://www.w3.org/2001/XMLSchema#>
PREFIX owl:      <http://www.w3.org/2002/07/owl#>
PREFIX swrl:     <http://www.w3.org/2003/11/swrl#>
PREFIX swrlb:    <http://www.w3.org/2003/11/swrlb#>
PREFIX vitro:    <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>
PREFIX bibo:     <http://purl.org/ontology/bibo/>
PREFIX c4o:      <http://purl.org/spar/c4o/>
PREFIX cito:     <http://purl.org/spar/cito/>
PREFIX event:    <http://purl.org/NET/c4dm/event.owl#>
PREFIX fabio:    <http://purl.org/spar/fabio/>
PREFIX foaf:     <http://xmlns.com/foaf/0.1/>
PREFIX geo:      <http://aims.fao.org/aos/geopolitical.owl#>
PREFIX obo:      <http://purl.obolibrary.org/obo/>
PREFIX ocrer:    <http://purl.org/net/OCRe/research.owl#>
PREFIX ocresd:   <http://purl.org/net/OCRe/study_design.owl#>
PREFIX skos:     <http://www.w3.org/2004/02/skos/core#>
PREFIX vcard:    <http://www.w3.org/2006/vcard/ns#>
PREFIX vitro-public: <http://vitro.mannlib.cornell.edu/ns/vitro/public#>
PREFIX vivo:     <http://vivoweb.org/ontology/core#>
PREFIX scires:   <http://vivoweb.org/ontology/scientific-research#>
PREFIX fo: <http://www.w3.org/1999/XSL/Format#>
PREFIX bio: <http://purl.org/vocab/bio/0.1/>


SELECT DISTINCT ?inclabel ?alabel ?blabel
WHERE {
  
  ?s ?p ?o.
  
  ?o a bibo:Document.

   
  ?o rdfs:label ?inclabel.
  ?a rdfs:label ?alabel.
  ?b rdfs:label ?blabel.
  
  
}


